// Generated by https://quicktype.io

export interface Info {
  titulo:         string;
  email:          string;
  nombre:         string;
  linkenid:       string;
  twitter:        string;
  facebook:       string;
  instagram:      string;
  tublr:          string;
  pinterest:      string;
  equipo_trabajo: any[];
}
